# -*- coding: utf-8 -*-
# Copyright 2021 IZI PT Solusi Usaha Mudah

from odoo import api, fields, models


class ProductTemplate(models.Model):
    _inherit = 'product.template'

    map_line_ids = fields.One2many(comodel_name="mp.map.product.line", inverse_name="product_tmpl_id",
                                   string="Mapped Lines", readonly=True)
    generated_by_mapping = fields.Boolean(string="Generated by Mapping?", default=False)
    product_map_ref = fields.Char(string="Product Map Ref.", readonly=True)
    mp_product_ids_ref = fields.Char(string="MP Product IDs Ref.", readonly=True)
