# -*- coding: utf-8 -*-
# Copyright 2021 IZI PT Solusi Usaha Mudah

from odoo import api, fields, models


class Product(models.Model):
    _inherit = 'product.product'

    generated_by_mapping = fields.Boolean(string="Generated by Mapping?", default=False)
    product_map_ref = fields.Char(string="Product Map Ref.", readonly=True)
